### ISSUE TITLE
getting compilation error for login component

### ISSUE THREAD

**Issue by pkjoshisbp** [thisiszoaib/angular-sign-up#1]
```
 const {email, password} = this.loginForm.value;
    this.authService.login(email, password).pipe(
 the email is showing with red underline.

```
Error: src/app/login/login.component.ts:40:28 - error TS2345: Argument of type 'string | null | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

40     this.authService.login(email, password).pipe(
                              ~~~~~

**Comment by thisiszoaib** [comment]
Fixed by updating to Angular 14 and Typed forms. Also check out this video for details.

https://youtu.be/__g3JO7eTnI
